Face_Verification_based_Attendance_system-master/ai_attendance_system/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name = 'home'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('searchattendance/', views.searchAttendance, name='searchattendance'),
    path('addstudent/', views.addStudent, name='addstudent'),
    # path('takeattendance/', views.takeAttendance, name='takeattendance'),
    path('account/', views.facultyProfile, name='account'),

    path('updateStudentRedirect/', views.updateStudentRedirect, name='updateStudentRedirect'),
    path('updateStudent/', views.updateStudent, name='updateStudent'),
    path('studentUpdate/', views.studentUpdate, name='studentUpdate'),   #new
    path('attendance/', views.takeAttendance, name='attendance'),
    path('camera/', views.camera, name='camera'),
    path('saveAttendance/', views.saveAttendance, name='saveAttendance'),

    # path('video_feed/', views.videoFeed, name='video_feed'),
    # path('videoFeed/', views.getVideo, name='videoFeed'),
]

Face_Verification_based_Attendance_system-master/artificial_intelligence_based_attendance_system/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ai_attendance_system.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Face_Verification_based_Attendance_system-master/ai_attendance_system/models.py
from django.db import models

from django.contrib.auth.models import User


def user_directory_path(instance, filename): 
    name, ext = filename.split(".")
    name = instance.firstname + instance.lastname
    filename = name +'.'+ ext 
    return 'Faculty_Images/{}'.format(filename)

class Faculty(models.Model):

    user = models.OneToOneField(User, null = True, blank = True, on_delete= models.CASCADE)
    firstname = models.CharField(max_length=200, null=True, blank=True)
    lastname = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    profile_pic = models.ImageField(upload_to=user_directory_path ,null=True, blank=True)

    def __str__(self):
        return str(self.firstname + " " + self.lastname)


def student_directory_path(instance, filename): 
    name, ext = filename.split(".")
    name = instance.registration_id # + "_" + instance.branch + "_" + instance.year + "_" + instance.section
    filename = name +'.'+ ext 
    return 'Student_Images/{}/{}/{}/{}'.format(instance.branch,instance.year,instance.section,filename)

class Student(models.Model):

    BRANCH = (
        ('CSE','CSE'),
        ('IT','IT'),
        ('ECE','ECE'),
        ('CHEM','CHEM'),
        ('MECH','MECH'),
        ('EEE','EEE'),
    )
    YEAR = (
        ('1','1'),
        ('2','2'),
        ('3','3'),
        ('4','4'),
    )
    SECTION = (
        ('A','A'),
        ('B','B'),
        ('C','C'),
    )

    firstname = models.CharField(max_length=200, null=True, blank=True)
    lastname = models.CharField(max_length=200, null=True, blank=True)
    registration_id = models.CharField(max_length=200, null=True)
    branch = models.CharField(max_length=100, null=True, choices=BRANCH)
    year = models.CharField(max_length=100, null=True, choices=YEAR)
    section = models.CharField(max_length=100, null=True, choices=SECTION)
    profile_pic = models.ImageField(upload_to=student_directory_path ,null=True, blank=True)


    def __str__(self):
        return str(self.registration_id)

class Attendance(models.Model):
    # faculty = models.ForeignKey(Faculty, null = True, on_delete= models.SET_NULL)
    student = models.ForeignKey(Student, null = True, on_delete= models.SET_NULL)
    Faculty_Name = models.CharField(max_length=200, null=True, blank=True)
    Student_ID = models.CharField(max_length=200, null=True, blank=True)
    date = models.DateField(auto_now_add = True, null = True)
    time = models.TimeField(auto_now_add=True, null = True)
    branch = models.CharField(max_length=200, null = True)
    year = models.CharField(max_length=200, null = True)
    section = models.CharField(max_length=200, null = True)
    period = models.CharField(max_length=200, null = True)
    status = models.CharField(max_length=200, null = True, default='Absent')
    # def __str__(self):
    #     return str(self.Student_ID + "_" + str(self.date)+ "_" + str(self.period))

Face_Verification_based_Attendance_system-master/ai_attendance_system/forms.py
from django.forms import ModelForm

from .models import *

class CreateStudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(CreateStudentForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['required'] = 'True'
    
class FacultyForm(ModelForm):
    class Meta:
        model = Faculty
        fields = '__all__'
        exclude = ['user']
    def __init__(self, *args, **kwargs):
        super(FacultyForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'    

Face_Verification_based_Attendance_system-master/ai_attendance_system/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, StreamingHttpResponse

from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .forms import *
from .models import Student, Attendance
from .filters import AttendanceFilter
from django.views.decorators.csrf import csrf_exempt
import requests
from django.contrib.admin.widgets import AdminDateWidget



# from django.views.decorators import gzip

from .recognizer import Recognizer
from datetime import date


import face_recognition
import numpy as np
import cv2
import os

from django.http import JsonResponse
# session
s = requests.Session()

names = []
formdetails = {}

@login_required(login_url = 'login')
def home(request):
    studentForm = CreateStudentForm()

    if request.method == 'POST':
        studentForm = CreateStudentForm(data = request.POST, files=request.FILES)
        # print(request.POST)
        stat = False 
        try:
            student = Student.objects.get(registration_id = request.POST['registration_id'])
            stat = True
        except:
            stat = False
        if studentForm.is_valid() and (stat == False):
            studentForm.save()
            name = studentForm.cleaned_data.get('firstname') +" " +studentForm.cleaned_data.get('lastname')
            messages.success(request, 'Student ' + name + ' was successfully added.')
            return redirect('home')
        else:
            messages.error(request, 'Student with Registration Id '+request.POST['registration_id']+' already exists.')
            return redirect('home')

    context = {'studentForm':studentForm}
    return render(request, 'ai_attendance_system/home.html', context)


def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username = username, password = password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Username or Password is incorrect')

    context = {}
    return render(request, 'ai_attendance_system/login.html', context)

@login_required(login_url = 'login')
def logoutUser(request):
    logout(request)
    return redirect('login')

@login_required(login_url = 'login')
def updateStudentRedirect(request):

    context = {}
    if request.method == 'POST':
        try:
            reg_id = request.POST['reg_id']
            branch = request.POST['branch']
            student = Student.objects.get(registration_id = reg_id, branch = branch)
            updateStudentForm = CreateStudentForm(instance=student)
            context = {'form':updateStudentForm, 'prev_reg_id':reg_id, 'student':student}
        except:
            messages.error(request, 'Student Not Found')
            return redirect('home')
    return render(request, 'ai_attendance_system/student_update.html', context)

@login_required(login_url = 'login')
def updateStudent(request):
    if request.method == 'POST':
        context = {}
        try:
            student = Student.objects.get(registration_id = request.POST['prev_reg_id'])
            updateStudentForm = CreateStudentForm(data = request.POST, files=request.FILES, instance = student)
            if updateStudentForm.is_valid():
                updateStudentForm.save()
                messages.success(request, 'Updation Success')
                return redirect('home')
        except:
            messages.error(request, 'Updation Unsucessfull')
            return redirect('home')
    return render(request, 'ai_attendance_system/student_update.html', context)


@login_required(login_url = 'login')
def takeAttendance(request):
    if request.method == 'POST':
        details = {
            'branch':request.POST['branch'],
            'year': request.POST['year'],
            'section':request.POST['section'],
            'period':request.POST['period'],
            'faculty':request.user.faculty
            }
        if Attendance.objects.filter(date = str(date.today()),branch = details['branch'], year = details['year'], section = details['section'],period = details['period']).count() != 0 :
            messages.error(request, "Attendance already recorded.")

            return JsonResponse({'status':True,'message':'Already recorded', 'url': 'http://127.0.0.1:8000'})
            # return redirect('home')
        else:
            s.formdetails = details
            
            return JsonResponse({'status':True,'message':'Plese record', 'url': ''})
            # students = Student.objects.filter(branch = details['branch'], year = details['year'], section = details['section'])
            # # camera()
            # names = Recognizer(details)
            # for student in students:
            #     if str(student.registration_id) in names:
            #         attendance = Attendance(Faculty_Name = request.user.faculty, 
            #         Student_ID = str(student.registration_id), 
            #         period = details['period'], 
            #         branch = details['branch'], 
            #         year = details['year'], 
            #         section = details['section'],
            #         status = 'Present')
            #         attendance.save()
            #     else:
            #         attendance = Attendance(Faculty_Name = request.user.faculty, 
            #         Student_ID = str(student.registration_id), 
            #         period = details['period'],
            #         branch = details['branch'], 
            #         year = details['year'], 
            #         section = details['section'])
            #         attendance.save()
            # attendances = Attendance.objects.filter(date = str(date.today()),branch = details['branch'], year = details['year'], section = details['section'],period = details['period'])
            # context = {"attendances":attendances, "ta":True}
            # messages.success(request, "Attendance taking Success")
            # return render(request, 'ai_attendance_system/attendance.html', context)        
    context = {}
    return render(request, 'ai_attendance_system/take_attendance.html', context)

def searchAttendance(request):
    # attendances = Attendance.objects.all()
    x = list(request.GET.keys())
    to_date = date.today()


    print("to_date")
    print(to_date)
    flag = 0
    if(x.count('from_date') and  request.GET['from_date'] != ''):
        from_date = request.GET['from_date']
        flag = 1
    
    if(x.count('to_date') and  request.GET['to_date'] != ''):
        to_date = request.GET['to_date']



    if(flag == 1):
        attendances = Attendance.objects.filter(date__lte=to_date,date__gte=from_date)
    else:
        attendances = Attendance.objects.all()

    # print()
    print("request.GET")

   


    myFilter = AttendanceFilter( request.GET, queryset=attendances)
    attendances = myFilter.qs
    # attendances = attendances
    context = {'myFilter':myFilter, 'attendances': attendances, 'ta':False}
    return render(request, 'ai_attendance_system/attendance.html', context)


def facultyProfile(request):
    faculty = request.user.faculty
    form = FacultyForm(instance = faculty)
    context = {'form':form}
    return render(request, 'ai_attendance_system/facultyForm.html', context)






def addStudent(request):
    studentForm = CreateStudentForm()

    if request.method == 'POST':
        studentForm = CreateStudentForm(data = request.POST, files=request.FILES)
        # print(request.POST)
        stat = False 
        try:
            student = Student.objects.get(registration_id = request.POST['registration_id'])
            stat = True
        except:
            stat = False
        if studentForm.is_valid() and (stat == False):
            studentForm.save()
            name = studentForm.cleaned_data.get('firstname') +" " +studentForm.cleaned_data.get('lastname')
            messages.success(request, 'Student ' + name + ' was successfully added.')
            return redirect('home')
        else:
            messages.error(request, 'Student with Registration Id '+request.POST['registration_id']+' already exists.')
            return redirect('home')

    context = {'studentForm':studentForm}
    return render(request, 'ai_attendance_system/add_student.html', context)

# def takeAttendance(request):
    studentForm = CreateStudentForm()

    if request.method == 'POST':
        studentForm = CreateStudentForm(data = request.POST, files=request.FILES)
        # print(request.POST)
        stat = False 
        try:
            student = Student.objects.get(registration_id = request.POST['registration_id'])
            stat = True
        except:
            stat = False
        if studentForm.is_valid() and (stat == False):
            studentForm.save()
            name = studentForm.cleaned_data.get('firstname') +" " +studentForm.cleaned_data.get('lastname')
            messages.success(request, 'Student ' + name + ' was successfully added.')
            return redirect('home')
        else:
            messages.error(request, 'Student with Registration Id '+request.POST['registration_id']+' already exists.')
            return redirect('home')

    context = {'studentForm':studentForm}
    return render(request, 'ai_attendance_system/home.html', context)



def studentUpdate(request):
    context = {}
    if request.method == 'POST':
        try:
            reg_id = request.POST['reg_id']
            branch = request.POST['branch']
            student = Student.objects.get(registration_id = reg_id, branch = branch)
            updateStudentForm = CreateStudentForm(instance=student)
            context = {'form':updateStudentForm, 'prev_reg_id':reg_id, 'student':student}

Face_Verification_based_Attendance_system-master/ai_attendance_system/templates/ai_attendance_system/add_student.html
{% extends 'ai_attendance_system/main.html' %}

{% block content %}

<div id="addstudent">
<br><br>
</div>
<div class="col-md-6" style="margin-top: 20px; margin-left: 450px;" >
    <div class="card card-body" >
        <center><h3>Add Student</h3></center>
        <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Enter First Name:</label>
                        {{ studentForm.firstname }}
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Enter Last Name:</label>
                        {{ studentForm.lastname }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="control-label">Enter Registration ID:</label>
                        {{ studentForm.registration_id }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="sel1">Select Branch:</label>
                        {{ studentForm.branch }}
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="sel1">Select Year:</label>
                        {{ studentForm.year }}
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="sel1">Select Section:</label>
                        {{ studentForm.section }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <div class="form-group" style="border: none;">
                        <label class="control-label">Upload Profile Picture:</label>
                        {{ studentForm.profile_pic }}
                    </div>
                {% comment %} <div>
                    {%if student.profile_pic %} {% endcomment %}
                    
                    <img id="imagePreviewOne" thumbnail src=""/>
                    {% comment %} <img src="{{student.profile_pic.url}}"> {% endcomment %}
                    {% comment %} {%endif%} {% endcomment %}
                </div>
                <div class="col-md-3"></div>
            </div>
            <button type="submit" class="btn btn-block btn-info">Submit</button>    
        </form>
    </div>
</div>

<script>
    var Element = document.getElementById('id_profile_pic');
    var img = document.getElementById('imagePreviewOne');
    Element.addEventListener('change', function() {
      var url = URL.createObjectURL(Element.files[0]);
      img.src = url;
      console.log(url);
});




$('html, body').animate({
        scrollTop: $("#addstudent").offset().top
    }, 2000);
</script>

{% endblock %}

Face_Verification_based_Attendance_system-master/ai_attendance_system/templates/ai_attendance_system/app1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Camera</title>
</head>
<body>
   
    <img style="display: block;-webkit-user-select: none;margin: auto;background-color: hsl(0, 0%, 25%);" src="/camera/">
    <a href="{% url 'saveAttendance' %}">Save</a>
    
</body>

</html>

Face_Verification_based_Attendance_system-master/ai_attendance_system/templates/ai_attendance_system/attendance.html
{% extends 'ai_attendance_system/main.html' %}

{% block content %}
{% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% else %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endif %}
	{% endfor %}
{% if ta == False %}
<div id="searchattendance">
    <br><br><br><br>
</div>


<center><h1 class="fontwhite">Search Attendance</h1></center>
<div class="row">
	<div class="col">
		<div class="card card-body">

			<center>

				<form method="get">
					<label for="id_Student_ID">Student ID:</label>
					<input type="text" name="Student_ID" id="id_Student_ID">
					<label for="from_date">From Date:</label>
					<input type="text" name="from_date" id="from_date">
					<label for="to_date">To Date:</label>
					<input type="text" name="to_date" id="to_date">
					<label for="id_year">Year:</label>
					<input type="text" name="year" id="id_year">
					<label for="id_period">Period:</label>
					<input type="text" name="period" id="id_period">
					<br>
					<button class="btn btn-primary" type="submit">Search</button>
				</form>
			</center>
		</div>
	</div>
</div>
<br>

<div class="row">
	<div class="col-sm-12">
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th>Student ID</th>
					<th>Branch</th>
					<th>Year</th>
					<th>Section</th>
					<th>Period</th>
					<th>Status</th>
					<th>Date</th>
					<th>Time</th>
				</tr>

				{% for attendance in attendances %}

				<tr>
                    <td>{{ attendance.Student_ID }}</td>					
					<!-- <td>{{ attendance.student.firstname }}</td>
                    <td>{{ attendance.Student_ }}</td> -->
					<td>{{ attendance.branch }}</td>
					<td>{{ attendance.year }}</td>
					<td>{{ attendance.section }}</td>
					<td>{{ attendance.period }}</td>
					<td>
						{%if attendance.status == 'Present' %}
						 
							<span class="badge badge-pill badge-success">{{ attendance.status }}</span>

						{% else %}
							<span class="badge badge-pill badge-danger">{{ attendance.status }}</span>

						{% endif %}

					</td>
					<td>{{ attendance.date }}</td>
					<td>{{ attendance.time }}</td>
				</tr>
				{% endfor %}

			</table>
		</div>
	</div>
</div>
{% else %}
<div>
	<a class="btn btn-warning" href="{% url 'home' %}"> &#8592; Back to Home</a>
</div>
	<center><h1 class="fontwhite">Present Period Attendance</h1></center>
	<div class="row">
		<div class="col-sm-12">
			<div class="card card-body">
				<table class="table table-sm">
					<tr>
						<th>Student ID</th>
						<th>Branch</th>
						<th>Year</th>
						<th>Section</th>
						<th>Period</th>
						<th>Status</th>
					</tr>
	
					{% for attendance in attendances %}
	
					<tr>
						<td>{{ attendance.Student_ID }}</td>
						<td>{{ attendance.branch }}</td>
						<td>{{ attendance.year }}</td>
						<td>{{ attendance.section }}</td>
						<td>{{ attendance.period }}</td>
						<td>{{ attendance.status }}</td>
					</tr>
					{% endfor %}
	
				</table>
			</div>
		</div>
	</div>
	



{% endif %}

<script>
	$('html, body').animate({
		scrollTop: $("#searchattendance").offset().top
	}, 2000);
</script>

{% endblock %}

Face_Verification_based_Attendance_system-master/ai_attendance_system/templates/ai_attendance_system/facultyForm.html
{%  extends 'ai_attendance_system/main.html' %}
{% block content %}




<div id="account">
    <br><br>
</div>

<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>

<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<a class="btn btn-warning" href="{% url 'home' %}"> &#8592; Back to Home</a>
			<hr>
			<h3 style="text-align: center">Faculty Profile Pic</h3>
			<hr>
			<img class="img-responsive profile-pic" src="{{request.user.faculty.profile_pic.url}}" >
		
		</div>
	</div>
	<div class="col-md-9">
		<div class="card card-body">
			
			<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}
		
			<input class="btn btn-primary" type="submit" name="Update Information">
			</form>
		</div>
	</div>
</div>


<script>
	$('html, body').animate({
	   scrollTop: $("#account").offset().top
   }, 2000);
</script>

{% endblock %}

Face_Verification_based_Attendance_system-master/ai_attendance_system/templates/ai_attendance_system/home.html
{% extends 'ai_attendance_system/main.html' %}

{% block content %}
<div class="container">
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% else %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
   

    
    
</div>

<!-- new code 1
 -->
 <section class="section-services">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-md-10 col-lg-8">
                <div class="header-section">
                    <h2 class="title">Exclusive <span>Services</span></h2>
                    <p class="description">There are many services we serve you through this system.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- Start Single Service -->
            
                <div class="col-md-6 col-lg-6">
                    <a href="{% url 'attendance' %}"  style="text-decoration:none" >
                        <div class="single-service">
                            <div class="part-1">
                                <i class="fa fa-camera "></i>
                                <h3 class="title">Take attendance</h3>
                                <p class="description">You can take attendance using our face recognition system.</p> 
                            </div>
                            
                        </div>
                    </a>
                </div>
           

            <!-- / End Single Service -->
            <!-- Start Single Service -->
            
            <div class="col-md-6 col-lg-6">
                <a href="{% url 'addstudent' %}"  style="text-decoration:none">
                    <div class="single-service">
                        <div class="part-1">
                            <i class="fa fa-plus"></i>
                            <h3 class="title">Add student</h3>
                            <p class="description">Add your student's information to store them in the system.</p>
                        </div>
                        
                    </div>
                </a>
            </div>
            
            <!-- / End Single Service -->
            <!-- Start Single Service -->
        
            <div class="col-md-6 col-lg-6">
                <a href="{% url 'studentUpdate' %}"  style="text-decoration:none">
                    <div class="single-service">
                        <div class="part-1">
                            <i class="fa fa-upload"></i>
                            <h3 class="title">Update student</h3>
                            <p class="description">Update the student's information </p>
                        </div>
                        
                    </div>
                </a>
            </div>
           
            <!-- / End Single Service -->
            <!-- Start Single Service -->
           
            <div class="col-md-6 col-lg-6">
                <a href="{% url 'searchattendance' %}"  style="text-decoration:none">
                    <div class="single-service">
                        <div class="part-1">
                            <i class="fa fa-search"></i>
                            <h3 class="title">Search attendance</h3>
                            <p class="description">Search the student's attendance information in our system.</p>
                        </div>
                    
                    </div>
                </a>
            </div>
           
        </div>
    </div>
</section>

{% endblock %}

Face_Verification_based_Attendance_system-master/ai_attendance_system/templates/ai_attendance_system/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<!-- <div class="mt-4">
					<div class="d-flex justify-content-center links">
						Forgot Password? <a href="" class="ml-2">Reset Password</a>
					</div>
			
				</div> -->
			</div>
		</div>
	</div>
</body>

</html>

Face_Verification_based_Attendance_system-master/ai_attendance_system/templates/ai_attendance_system/videoFeed.html
{% extends 'ai_attendance_system/main.html' %}

{% block content %}
    <img src="{% url 'video_feed' %}">
{% endblock %}